### ISSUE TITLE
Fix 'Unnecessary "else" after "return"' issue in PynPoint\ProcessingModules\TimeDenoising.py

### ISSUE THREAD

**Issue by tomasstolker** [PynPoint/PynPoint#189]
[CodeFactor](https://www.codefactor.io/repository/github/pynpoint/pynpoint/overview/master) found an issue: Unnecessary "else" after "return"

It's currently on:
[PynPoint\ProcessingModules\TimeDenoising.py:179
](https://www.codefactor.io/repository/github/pynpoint/pynpoint/source/master/PynPoint/ProcessingModules/TimeDenoising.py#L179)

**Comment by majobodo** [comment]
will be solved together with wavelet documentation and clean up
