### ISSUE TITLE
Fix 'Consider using enumerate instead of iterating with range and len' issue in PynPoint\ProcessingModules\TimeDenoising.py

### ISSUE THREAD

**Issue by tomasstolker** [PynPoint/PynPoint#190]
[CodeFactor](https://www.codefactor.io/repository/github/pynpoint/pynpoint/overview/master) found an issue: Consider using enumerate instead of iterating with range and len

It's currently on:
[PynPoint\ProcessingModules\TimeDenoising.py:82
](https://www.codefactor.io/repository/github/pynpoint/pynpoint/source/master/PynPoint/ProcessingModules/TimeDenoising.py#L82)

**Comment by majobodo** [comment]
will be solved together with wavelet documentation and clean up
