### ISSUE TITLE
Fix 'Consider changing "not wavelet in ['dog', 'morlet']" to "wavelet not in ['dog', 'morlet']"' issue in PynPoint\ProcessingModules\TimeDenoising.py

### ISSUE THREAD

**Issue by tomasstolker** [PynPoint/PynPoint#198]
[CodeFactor](https://www.codefactor.io/repository/github/pynpoint/pynpoint/overview/master) found an issue: Consider changing "not wavelet in ['dog', 'morlet']" to "wavelet not in ['dog', 'morlet']"

It's currently on:
[PynPoint\ProcessingModules\TimeDenoising.py:28
](https://www.codefactor.io/repository/github/pynpoint/pynpoint/source/master/PynPoint/ProcessingModules/TimeDenoising.py#L28)

**Comment by majobodo** [comment]
will be solved together with wavelet documentation and clean up
