### ISSUE TITLE
Fix 'The if statement can be replaced with 'var = bool(test)'' issue in PynPoint\ProcessingModules\TimeDenoising.py

### ISSUE THREAD

**Issue by tomasstolker** [PynPoint/PynPoint#199]
[CodeFactor](https://www.codefactor.io/repository/github/pynpoint/pynpoint/overview/master) found an issue: The if statement can be replaced with 'var = bool(test)'

It's currently on:
[PynPoint\ProcessingModules\TimeDenoising.py:102
](https://www.codefactor.io/repository/github/pynpoint/pynpoint/source/master/PynPoint/ProcessingModules/TimeDenoising.py#L102)

**Comment by majobodo** [comment]
will be solved together with wavelet documentation and clean up
