### ISSUE TITLE
Multiprocessing contrastcurve images array too large

### ISSUE THREAD

**Issue by 404NotFoundv2** [PynPoint/PynPoint#302]
When the array images in the contrastcurve (argument 'images') module becomes too large (> 2 GB), the multiprocessing package can not handle it as some implementations are made in 32-bit. The error I get is
```python
Running ContrastCurveModuleTraceback (most recent call last):
.
.
File "/scratch/jjonker/jasper_test_3/lib/python3.6/site-packages/multiprocess/connection.py", line 396, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```
(2^31 = 2147483648). 
It seems like this is a limitation of how python implemented this module. So the array has to be split in chunks smaller than 2GB, or the use of sharedmemory(?), or...?

Here some info:
[Link1](https://stackoverflow.com/a/16576454)
[Link2](https://bugs.python.org/issue17560)

**Comment by 404NotFoundv2** [comment]
It seems like it can be solved by using sharedmemory.

I implemented it as follows and it seems to be working:

At the top of the file (I think it is preinstalled with numpy, otherwise pip it):
```python
import sharedmem
```
Then change the lines where you call multiprocessing.map(...) to:
```python
image = sharedmem.empty(images.shape)
image[:,:,:] = images[:,:,:]

pool = multiprocessing.Pool(processes=cpu)

func = functools.partial(contrast_limit, image, psf, parang, self.m_psf_scaling, \
                                     self.m_extra_rot, self.m_magnitude, self.m_pca_number, \
                                     self.m_threshold, self.m_accuracy, self.m_aperture, \
                                     self.m_ignore, self.m_cent_size, self.m_edge_size, pixscale)

result = pool.map(func, positions)

pool.close()
pool.join()
```
The size of images was in this case ~2.1 GB. Note that for even a limited number of cpu (in this case 6) the ram usage is very big (~150-200 GB). But for smaller datasets this might not be the case.

You can see it also in my fork [here](https://github.com/404NotFoundv2/PynPoint/blob/master/pynpoint/processing/limits.py)

**Comment by tomasstolker** [comment]
Thanks for finding a solution to this problem, @404NotFoundv2.

The easiest would be if you put the changes in a separate branch of your fork and create a pull request from there. Or, I can create the pull request myself, if you insist ;). Let me know if you have any questions.
