### ISSUE TITLE
WaveletTimeDenoisingModule padding

### ISSUE THREAD

**Issue by amuellerastro** [PynPoint/PynPoint#385]
@majobodo 
When I apply the WaveletTimeDenoisingModule and the padding value is set to 'zero' or 'mirror' it happens that the resulting array has one frame less resulting the following modules to crash since they expect the original number of frames. This seems to happen for arrays with even elements.

**Comment by tomasstolker** [comment]
Additional test cases were added with PR #394 but the bug has not appeared. Please reopen the issue with additional details if there is in fact a bug that is not catched by the test cases.
