### ISSUE TITLE
Screen output from the ContrastCurveModule

### ISSUE THREAD

**Issue by tomasstolker** [PynPoint/PynPoint#386]
The output printed to the screen has a small bug when the module has finished:

`Running ContrastCurveModule... [DONE]- ETA: 00:00:03`

which should be:

`Running ContrastCurveModule... [DONE]`

**Comment by tomasstolker** [comment]
@benassa-de-glassa is this something you could fix? Thanks.

**Comment by benassa-de-glassa** [comment]
yes, I'll have a look into it

**Comment by benassa-de-glassa** [comment]
my proposed fix is in #387

**Comment by tomasstolker** [comment]
I have fixed the problem with commit 6d82bd73724c42fce3b05327eca8da15227ba3db.
